classDiagram

    %% java.lang
    class AutoCloseable {
      <<interface>>
    }

    %% java.lang
    class RuntimeException {

    }

    %% pt.tecnico.uilib
    class Dialog {
      -ACTION_CHANNEL : String = "ui" %% STATICF
      -CHANNEL_SWING : String = "swing" %% STATICF
      -CHANNEL_NEW_SWING : String = "newswing" %% STATICF
      -CHANNEL_TEXT : String = "text" %% STATICF

      +open(menu: Menu) void
      +fill(form: Form) void
      +render(title: String, text: String) void
      +close() void
    }

    %% pt.tecnico.uilib
    class Display {
      -_title: String
      -_text: StringBuilder
      +add(toAdd: Object) Display 
      +addAll(items: Collection~?~) Display
      +addLine(toAdd: Object) Display
      +addNewLine(toAdd: Object, force: boolean) Display
      +display() void
      +popup(toPop: Object) void
      +popup(toPop: Collection~?~) void
      +clear() void
    }

    %% pt.tecnico.uilib
    class InteractionDriver {
      <<interface>>
      +open(menu: Menu) void
      +fill(form: Form) void
      +render(title: String, text: String) void
      +close() void
    }

    %% pt.tecnico.uilib.menus
    class Menu {
      -_title: String

      +title() String
      +size() int
      +entry(n: int) Command~question~
      +entries() array_Command~question~
      +open() void
    }

    %% pt.tecnico.uilib.menus
    class Command~Receiver~ {
      <<abstract>>
      -_last: boolean
      -_title: String
      #<<final>> _receiver: Receiver
      #_valid: Predicate~Receiver~

      +title() String final
      +isLast() boolean
      +isValid() boolean
      +addBooleanField(key: String, prompt: String) void
      +addRealField(key: String, prompt: String) void
      +addIntegerField(key: String, prompt: String) void
      +addStringField(key: String, prompt: String) void
      +booleanField(key: String) Boolean
      +realField(key: String) Double
      +integerField(key: String) Integer
      +stringField(key: String) String
      +<<final>> performCommand() void 
      +execute()* void
    }

    %% pt.tecnico.uilib.menus
    class CommandException {
      
    }

    %% pt.tecnico.uilib.menus
    class DoOpenMenu {
      #execute() void final
    }

    %% pt.tecnico.uilib.forms
    class Form {
      -_title: String
      -_fields: Map<String, Field<?>>
      +title() String
      +entries() Collection~Field_question~
      +field(key: String) Field~question~
      -add(key: String, in: Field<?>) void
      +addBooleanField(key: String, label: String) void
      +addStringField(key: String, label: String) void
      +addRealField(key: String, label: String) void
      +addIntegerField(key: String, label: String) void
      -get(key: String, type: String) Object
      +booleanField(key: String) Boolean
      +stringField(key: String) String
      +realField(key: String) Double
      +integerField(key: String) Integer
      +parse() Form
      +parse(clear: boolean) Form
      +clear() void
      +confirm(prompt: String)$ Boolean
      +requestInteger(prompt: String)$ Integer
      +requestReal(prompt: String)$ Double
      +requestString(prompt: String)$ String
    }

    %% pt.tecnico.uilib.forms
    class FormException {
    }

    %% pt.tecnico.uilib.forms
    class Field~Type~ {
      <<abstract>>
      -_prompt: String
      -_clear: boolean
      #_value: Type

      +prompt() String
      +set(value: Type) void
      +value() Type
      +clear() void
      #dirty() void
      +cleared() boolean
      +isReadOnly() boolean
      parse(in: String)* boolean
    }

    %% pt.tecnico.uilib.forms
    class FieldBoolean {
      -BOOLEAN_WORD_YES: String = "sim" %% STATICF
      -BOOLEAN_WORD_NO: String = "nao" %% STATICF
      -BOOLEAN_CHAR_YES: char = 's' %% STATICF
      -BOOLEAN_CHAR_NO: char = 'n' %% STATICF

      +parse(in: String) boolean
    }

    %% pt.tecnico.uilib.forms
    class FieldInteger {
      +parse(in: String) boolean
    }

    %% pt.tecnico.uilib.forms
    class FieldNone {
      +parse(in: String) boolean
    }

    %% pt.tecnico.uilib.forms
    class FieldReal {
      +parse(in: String) boolean
    }

    %% pt.tecnico.uilib.forms
    class FieldString {
      +parse(in: String) boolean
    }

    %% pt.tecnico.uilib.text
    class CompositePrintStream {
      -_error: boolean

      ~<<final>> add(ps: PrintStream) void final
      
    }

    %% pt.tecnico.uilib.text
    class RuntimeEOFException {
      
    }

    %% pt.tecnico.uilib.text
    class TextInteraction {
      -_writeInput: boolean

      +close() void
      +open(menu: Menu) void
      +fill(form: Form) void
      +render(title: String, text: String) void
      -<<final>> readString(prompt: String) String
      -<<final>> readInteger(prompt: String) int
    }

    Dialog --> Dialog : UI 
    Dialog --> InteractionDriver : -_backend
    Dialog ..> Menu
    Dialog ..> Form
    Dialog ..|> AutoCloseable

    Display --> Dialog : -_ui

    InteractionDriver ..> Menu
    InteractionDriver ..> Form

    FieldBoolean --|> Field : <<bind>> Type->Boolean
    FieldInteger --|> Field
    FieldNone --|> Field
    FieldReal --|> Field
    FieldString --|> Field

    Form --> Dialog : -_ui

    FormException --|> RuntimeException
    RuntimeException --|> Exception

    Command --> Form : -<<final>> _form
    Command --> Display : #final _display
    Command ..> CommandException : throws

    CommandException --|> Exception

    DoOpenMenu --|> Command : <<bind>> Receiver->Menu

    Menu --> Dialog : -_ui
    Menu o--> Command : -_commands

    CompositePrintStream --|> PrintStream
    CompositePrintStream "0" o--> "*" PrintStream: _streams

    RuntimeEOFException --|> RuntimeException

    TextInteraction ..|> InteractionDriver
    TextInteraction --> BufferedReader: _in
    TextInteraction --> PrintStream: -_out
    TextInteraction --> PrintStream: -_log
    TextInteraction ..> IOException: throws
