name: CI
on: push

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: 'project'
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Place po-uilib in correct folder and compile it
        working-directory: project
        run: wget https://web.tecnico.ulisboa.pt/\~david.matos/w/pt/images/3/37/Po-uilib-202109221024.tar.bz2 && tar xvf Po-uilib-202109221024.tar.bz2 && mv po-uilib-202109221024 po-uilib && rm Po-uilib-202109221024.tar.bz2 && cd po-uilib && make && cd ..
      - name: Run makefile
        working-directory: project
        run: make compile
      - name: Checkout tests
        uses: actions/checkout@v2
        with:
          repository: diogotcorreia/proj-ist-unit-tests
          path: 'tests'
      - name: Configure tests
        working-directory: tests/po/2021-2022/po-p1
        run: echo "PROJECT_CLASSPATH=$(cd $GITHUB_WORKSPACE/project && echo "$(pwd)/po-uilib/po-uilib.jar:$(pwd)/ggc-app/ggc-app.jar:$(pwd)/ggc-core/ggc-core.jar")" > config
      - name: Run tests
        working-directory: tests/po/2021-2022/po-p1
        run: make

